### ISSUE TITLE
Horseshoe Bats were collected up till Dec-2017 for the WHIOV.

### ISSUE THREAD

**Issue by ribagi** [Project-Evidence/project-evidence.github.io#10]
I was reading through this project and saw sections, "_8.5.4 Paper 4_" and "_8.6.2 Horseshoe Bats Were Once Present in WHCDC Labs_". I found some information similar to this from the WHIOV official website. Sometime in February, I found a press release from the WHIOV website which details how scientists went into bat-caves in Yunnan. My Chinese isn't that good so I apologize for any bad translations.

> 地点，云南的这个洞，更值得我们关注。”从这一年开始，云南的这个蝙蝠洞被定为长期采样地点。

>一直到2015年10月，每年的春秋两季，石正丽研究团队都会到那里去。

>“春天是蝙蝠的繁殖季节，秋天则是冠状病毒检测出阳性率最高的季节。”胡犇解释。

>这个洞穴的温度大约在22℃到25°C之间，湿度在85%到90%左右。这里栖息着一个数量庞大的菊头蝠种群。在整个云南，类似的蝙蝠洞其实并不罕见。

This translates into:

>This bat-cave in Yunnan deserves our attention. "Starting this year, this bat-cave in Yunnan has been designated as a long term sampling location.

>Until October 2015, Shi Zhengli's research team will go there every spring and autumn.

>Spring is the breeding season for bats, and autumn is the season with the highest detection rate of coronavirus", Hu Ben explained.

>The temperature of this cave is about 22 to 25 Celsius, and the humidity is between 85% to 90%. This cave is a home to a huge population of horseshoe bats. Throughout Yunnan, similar bat caves are not uncommon.

Additionally this press release details on how they found SARS like viruses in horseshoe bats that can "infect humans".

>在实验室里，研究人员对这些样品进行了抗体与核酸检测。他们在菊头蝠种群中检测到了SARS冠状病毒抗体。不同地区的菊头蝠中，都检测到了“遗传多样的、与SARS病毒相类似的冠状病毒核酸”。样品中还有一株蝙蝠冠状病毒，全长基因组测序证明，它与能够感染人和果子狸的SARS冠状病毒，基因组序列相似度达到92%。

This translates into:

>In the laboratory, researchers conducted antibody and nucleic acid tests on these samples. They tested the horseshoe bat population with the SARS antibodies. "While genetically different, corona-virus nucleic acids similar are to the SARS virus have been detected in horseshoe bats in different regions". There is also a strain of bat corona-virus in the sample. The full-length genome sequencing proves that it has 92% genome sequence similarity with SARS corona-virus, with capable of infecting humans and civets.

http://www.whiov.cas.cn/xwdt_105286/kydt/201712/t20171214_4916301.html
Archive: http://archive.is/5t1yF

**Comment by Project-Evidence** [comment]
Thank you very much. We have included this press release in [Revision 2](project-evidence.github.io).
