### ISSUE TITLE
Wrong location of Wuhan Jianghan Disease Prevention and Control Center

### ISSUE THREAD

**Issue by zerolattice** [Project-Evidence/project-evidence.github.io#14]
The location on the map linked on project-evidence.github.io has changed since the screenshot. Chinese locations have not been accurate on Google Maps in the past, due to restrictions. The correct walking distance between Huanan Seafood Market and Wuhan CDC is most likely 0.5km.

### **Huanan Seafood Market (华南海鲜批发市场)**
https://en.wikipedia.org/wiki/Huanan_Seafood_Wholesale_Market#/map/0
https://ditu.amap.com/place/B0FFIKVHYC
https://mapcarta.com/W764859133
https://www.openstreetmap.org/?mlat=30.6196&mlon=114.2576&zoom=15#map=15/30.6179/114.2595
https://goo.gl/maps/RKS7zD4R3EJ8qPLCA
https://map.baidu.com/?shareurl=1&poiShareUid=43b7e889bff6636a58f6be33

![image](https://user-images.githubusercontent.com/61113971/79695998-501e3780-827a-11ea-9386-14eb26854f0f.png)
![image](https://user-images.githubusercontent.com/61113971/79696223-adff4f00-827b-11ea-87b2-e6740d5ae4a9.png)
![image](https://user-images.githubusercontent.com/61113971/79695491-6f679580-8277-11ea-93a8-eb373c77982d.png)

### **Wuhan Center for Disease Control and Prevention (武汉市疾病预防控制中心)**
https://www.whcdc.org/show/86.html
![image](https://user-images.githubusercontent.com/61113971/79694611-af2b7e80-8271-11ea-96c1-a0e593e5e825.png)

AutoNavi (Alibaba)
https://ditu.amap.com/place/B0FFLEZPOG
![image](https://user-images.githubusercontent.com/61113971/79694955-23672180-8274-11ea-8179-504162461f7c.png)

Baidu maps
https://maps.baidu.com/poi/%E6%AD%A6%E6%B1%89%E5%B8%82%E7%96%BE%E7%97%85%E9%A2%84%E9%98%B2%E6%8E%A7%E5%88%B6%E4%B8%AD%E5%BF%83/@12720364.522443516,3561568.412885041,18.96z?uid=5325f5ab08c15717fea7781e&ugc_type=3&ugc_ver=1&device_ratio=1&compat=1&querytype=detailConInfo&da_src=shareurl
![image](https://user-images.githubusercontent.com/61113971/79694987-5b6e6480-8274-11ea-89bf-5fc4e777cec1.png)

Google (currently)
https://goo.gl/maps/jGaLSzZb5tEzJNks9
![image](https://user-images.githubusercontent.com/61113971/79637971-58e01200-8183-11ea-8005-5e32fd99f380.png)

Google (previously)
![image](https://user-images.githubusercontent.com/61113971/79638041-c8560180-8183-11ea-9508-ab1044f0f5c0.png)

**Comment by Project-Evidence** [comment]
Thank you very much, we have incorporated this issue in [Revision 2](project-evidence.github.io).

**Comment by zerolattice** [comment]
Still wrong location of Wuhan Center for Disease Control and Prevention. Google Maps is *not* a reliable source within Chinese borders. Please compare Google Maps with whcdc.org, maps.baidu.com, amap.com and other map services. With Street View, it's even possible to walk between Huanan Seafood Market and Wuhan CDC. The distance is <500m.

https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China

**Comment by research-project-cov** [comment]
the Wuhan WIV P4 lab is not at the location of Wuhan Institute of Virology: the P4 lab is 40km from seafood market,  in Jiangxia district (where the 1 day constructed temprary hospital has been built), just beside the Huanan new material insdutrial park ; here the google link
https://www.google.fr/maps/place/Huanan+New+Materials+Industrial+Park/@30.3766708,114.261759,580m/data=!3m1!1e3!4m5!3m4!1s0x342eb615bad19889:0x1dedc0938dd64fac!8m2!3d30.376234!4d114.260838

and snapshot 
![image](https://user-images.githubusercontent.com/63962102/82055827-5fe63b80-96c1-11ea-9af2-2a1b49f9a39b.png)

**Comment by research-project-cov** [comment]
the itinary from huanan seafood market to P4 lab
https://www.google.fr/maps/dir/Huanan+Seafood+Market,+Fazhan+Avenue,+District+de+Jianghan,+Wuhan,+Hubei,+Chine/Huanan+New+Materials+Industrial+Park,+107%E5%9B%BD%E9%81%93+Jiangxia+District,+Wuhan,+Hubei,+Chine/@30.491712,114.062848,61647m/data=!3m2!1e3!4b1!4m15!4m14!1m5!1m1!1s0x342eaeb553b58fd7:0x355ff7d1fe8e8fb7!2m2!1d114.2622935!2d30.6165888!1m5!1m1!1s0x342eb615bad19889:0x1dedc0938dd64fac!2m2!1d114.260838!2d30.376234!3e0!5i2

**Comment by research-project-cov** [comment]
interesting video that clarifies several locations : huanan sea food market, P4 lab, Jiangxia district emergency station, railway station, military hospital https://www.youtube.com/watch?time_continue=8&v=phtkv8ktUKc&feature=emb_logo

**Comment by research-project-cov** [comment]
I see also a confusion on the location of Wuhan Center for Disease Prevention and Control: the address is 288 Machang Road, Wuhan, Hubei 430030 (close to the wet market).

**Comment by research-project-cov** [comment]
I try to recapitulate all labs, with correct locations, in this mark-up map; please complete if you have more info
![image](https://user-images.githubusercontent.com/63962102/82079814-c7ad7e00-96e3-11ea-91d5-4bd2c24a2492.png)

**Comment by research-project-cov** [comment]
inside the WIV main building (Keji road)
![image](https://user-images.githubusercontent.com/63962102/82080349-a9944d80-96e4-11ea-8bb5-a46239843ee6.png)
![image](https://user-images.githubusercontent.com/63962102/82080359-b153f200-96e4-11ea-96f9-336aa3f9468c.png)
![image](https://user-images.githubusercontent.com/63962102/82080387-bfa20e00-96e4-11ea-8c79-6434528eb9f9.png)
![image](https://user-images.githubusercontent.com/63962102/82080426-cfb9ed80-96e4-11ea-9724-7a59726737b4.png)
