### ISSUE TITLE
contributions would be easier if pre-build site source were available

### ISSUE THREAD

**Issue by rothos** [Project-Evidence/project-evidence.github.io#15]
Hard to make nontrivial contributions & hard to review pull requests when the whole doc is 20 lines of minified HTML. Not sure what your setup is, and maybe it's not worth it right now, but collaboration would be easier if the pre-build site source code were there in the repo.

Thanks for your work. Beautiful document.

**Comment by Project-Evidence** [comment]
We agree. This has been on the roadmap since the beginning.

In [Revision 2](project-evidence.github.io) we have added the "src" folder which provides the source code for the entire document. It is written in [Scribble](https://docs.racket-lang.org/scribble/index.html).

**Comment by rothos** [comment]
A+ thank yall
