### ISSUE TITLE
Can use any of the info here also: https://exposing-the-likely-wuhan-lab-leak.github.io/

### ISSUE THREAD

**Issue by EXPOSING-THE-LIKELY-WUHAN-LAB-LEAK** [Project-Evidence/project-evidence.github.io#17]
Hi, 

Thanks for uploading such a nice site on that topic! I worked for weeks researching and writing this: https://exposing-the-likely-wuhan-lab-leak.github.io/

The first edition was a PDF that was spread in early April and then uploaded on github. Imagine somebody on project-evidence.github.io saw exposing-the-likely-wuhan-lab-leak.github.io somewhere (maybe freenode) before. 

The project-evidence.github.io team is welcome to integrate any info from there that isn't already part of project-evidence.github.io. 

I haven't been so focused on making fancy HTML recently, so glad that project-evidence.github.io looks pleasantly formatted for the public to read.

**Comment by Project-Evidence** [comment]
Thank you for the collaboration. Your work is appreciated, and you are welcome to pull content from our document as well.

Please take a look at [Revision 2](project-evidence.github.io) and let us know if we failed to cover anything you covered.
