### ISSUE TITLE
Addressing the statement from Prof Edward Holmes

### ISSUE THREAD

**Issue by sbellem** [Project-Evidence/project-evidence.github.io#19]
Could probably fit in section "Addressing Counter-Claims".

Complete statement at https://www.sydney.edu.au/news-opinion/news/2020/04/16/COVID-19-statement-professor-edward-holmes-sars-cov-2-virus.html

> Unfounded speculation on the origins of the SARS-CoV-2 virus that causes COVID-19 has prompted the following statement from Professor Holmes, who was involved in mapping the genome of the virus.

> There is no evidence that SARS-CoV-2, the virus that causes COVID-19 in humans, originated in a laboratory in Wuhan, China.

### Disclaimer
I have no relevant expertise. I just wish to try to help as I am deeply disturbed and confused by the situation.

**Comment by EXPOSING-THE-LIKELY-WUHAN-LAB-LEAK** [comment]
Sadly standard disinfo BS from "scientists" concerened about bioresrarch lab industry profits.

**Comment by EXPOSING-THE-LIKELY-WUHAN-LAB-LEAK** [comment]
And yes, any supposed "scientist" or researcher that says SARS-COV-2 "couldn't have" come frok those Wuhan labs is blatantly lying or ignorant of Wuhan lab research papers. There is no question anymore about "could it have happened?" YES, SARS-COV-2 ABSOLUTELY COULD HAVE LEAKED FROM A WUHAN LAB. Confirmed research papers authored by those lab employees and also confirmed by experts such as Richard Ebright

**Comment by Project-Evidence** [comment]
We address this statement in [Revision 2](project-evidence.github.io).
