### ISSUE TITLE
Links for the news articles in section 8.6.3

### ISSUE THREAD

**Issue by caltaojihun** [Project-Evidence/project-evidence.github.io#20]
Section 8.6.3 contain the two referenced news article:
* Tao P. Expert in Wuhan collected ten thousands animals: capture bats in mountain at night. Changjiang Times 2017.
* Li QX, Zhanyao. Playing with elephant dung, fishing for sea bottom mud: the work that will change China’s future. thepaper 2019.

The link for the first article is [here](http://www.changjiangtimes.com/2017/05/567037.html) ([archived](https://archive.is/ruSFu)). The title doesn't seem to match the reference, but it does confirm that researcher Tian Junhua did isolate for 14 days due to bat blood.
Another [news article](http://www.xinhuanet.com//local/2017-05/03/c_1120909064_2.htm) ([archived](https://archive.is/zqJl9)) that also contain some images of Tian Junhua.

The original article for the second reference can be found [here](https://www.thepaper.cn/newsDetail_forward_5240333) ([archived](https://archive.is/PiqJt)). Rough translation corroborates the claim that researcher Tian Junhua came into contact with bat urine.

**Comment by sanxiyn** [comment]
Note on how to do this kind of research: it is easy to establish Tian Junhua is 田俊华, and bat is 蝙蝠. Armed with this knowledge, run [Baidu search](http://www.baidu.com/s?wd=%E7%94%B0%E4%BF%8A%E5%8D%8E%20%E8%9D%99%E8%9D%A0). (Baidu works much better than Google for Chinese sources.) http://www.changjiangtimes.com/2017/05/567037.html is the second result, with source 长江商报 (Changjiang Times) and date 2017年5月3日.
