### ISSUE TITLE
Status of project? Are issues and contributions looked at?

### ISSUE THREAD

**Issue by sbellem** [Project-Evidence/project-evidence.github.io#24]
Hi,

 thanks for your great work. I wonder whether you intent to process the open issues and pull requests.

I feel that such a project is meant to evolve, so I just wonder ...

Thank you!

**Comment by Project-Evidence** [comment]
Hello,

Thank you for reaching out. We have just published [Revision 2](project-evidence.github.io) which should address your concerns. We will be going through open issues now. :)
