### ISSUE TITLE
Documenting The Various Hypotheses

### ISSUE THREAD

**Issue by jonseymour** [Project-Evidence/project-evidence.github.io#37]
Given the intent of this document is to get to truth, wherever that truth may lie, I wonder if it might be worth documenting the various hypotheses and the arguments for and against these given the evidence available.

As it stands, the arguments against the natural origin are interspersed with the collection of the evidence, but there is no single place that conveys a coherent hypothesis about what has happened. This is a little unfair to the scientists concerned, because a lot of mud is being thrown at these scientists and they don't have much chance to defend themselves.

For example: is the hypothesis that both the WCDC and WIV were involved or just one of them, or can that change over time? 

What is the most parsimonious hypothesis? What would constitute a falsification of a hypothesis?

For example, the natural origin hypothesis would be strengthened by any discovery of an intermediate between RaTG13 and SARS-CoV-2 in the wild, it would be damaged by a failure to sequence and generate a viable virus from RaTG13 samples obtained from WIV or synthesised with genetic engineering techniques from the pubished sequence or by the discovery of an intermediate between RaTG13 and SARS-CoV-2 in the WIV lab.

How is/are the lab-leak theory (or theories) falsified? This work just becomes no different to conspiracy theory unless someone is prepared to standup and stick one (or more) falsifiable hypotheses in the ground so that they can be evaluated.

I write this as one who is a little bit suspicious of the coincidence that a wild virus that most likely originated in bat populations in Yunnan, suddenly crossed the species barrier in a city 1,000 miles away from its likely origin, a city that happens to have a BSL-4 lab which houses its nearest known relative (the fact that WIV has RaTG13 is not itself surprising - that is what they do after all: study bat viruses - the fact the outbreak occurred in Wuhan is). I am also sympathetic to the stated objective of this document to get to the truth, but I am concerned the document in the format as it stands is a collection of facts or almost facts that conspiracy theories will pick and choose to suit their own agendas.

I too would like to see the truth revealed (whatever it is), but I really want science to be on the right side of the truth when the happens. It will be much easier for science to defend against the weapon theorists, if it makes the right call on the lab origin hypothesis. If the scientific establishment denies a lab-origin hypothesis that turns out to be true, it will be incredibly damaging to science as a whole.

I think presenting one or more alternative hypotheses together with for and against arguments, would be a safer way to present the material. Each hypotheses stands and falls on the quality of the evidence advanced to support it and how falsifiable it is. The current approach allows the reader to grab evidence that happens to suit their own biased and unstated hypotheses without every really having to evaluate the quality fo the evidence for themselves. If one of the claims turns out to be false, does this allow the game of whack-a-mole to continue with the other claims?

**Comment by sanxiyn** [comment]
I agree outbreak at Wuhan is surprising. In my opinion, the most parsimonious hypothesis is that someone took a high speed train from Yunnan to Wuhan. Unlikely, yes, but obviously it happens, and it seems to be the most likely explanation.

**Comment by jonseymour** [comment]
@sanxiyn It is certainly the explanation with the smallest number of moving bits, but quite hard to verify one way or the other.

The next simplest would be that SARS-CoV-2 was not mutated from RaTG13 during the course of the research but was in fact a related, unpublished sibling of RaTG13. After all, the RaTG13 sequence was not published until the pandemic was upon us so there was at least one unpublished sequence being held by WIV.

You'd then have to explain KP876546/RaTG13 and SARS-CoV-2 happened to have an almost identical RdRp gene, but that isn't too hard, I think - evolution that occurred prior to sampling of all 2/3 specimens.  The main problem with such a theory is that there is no direct evidence to support it - it would be an unsubstantiated allegation that scientists knowingly withheld knowledge of possessing SARS-CoV-2 or a near relative. It is also a just-so theory, which happens to sidestep the argument in the Nature article. So, pointless as a hypothesis to put forward, since while it could be true, there is no way to prove it.

**Comment by Arakkun** [comment]
Well, the virus started from a "Seafood wet market" where most of the animals that do have a spike with this virus technically aren't sold. ( It is debatlable, for example, whether the Pangolin was really sold there ).
Add the fact that China's gov't has an intensive camera monitoring of the chinese, that makes it actually strange for the Wuhan gov't to actuially not trace a land animal being sold in a seafood market or such, or have problem tracing the virus in general (As most cases aren't traceable to the Seafood market). 
China is probably hiding things, whether it's just the real intensity of the outbreak (Aka, they had it from much, much before and want to appear "we acted ASAP!") or the place where it actually started.

Even just the "direct train from the Yunnan" hypothesis wouldn't be that much true. If China is to be "trusted", this virus HAD to transfer from Bat - to - X (where X is different enough from an human for the virus to not be dangerous for humans manipulating it, and as Bats aren't sold in Wuhan and aren't even awake technically), where X was captured and sold at the Seafood market making contact with a Y animal, where in this case, the virus could mutate and become infective for humans.
