### ISSUE TITLE
Could you discuss why the project name was changed?

### ISSUE THREAD

**Issue by jli** [Project-Evidence/project-evidence.github.io#4]

**Comment by Project-Evidence** [comment]
Hello,

We have added the following paragraph to Authors section:

> An earlier version of this document referred to us as "Project E.P.S.T.E.I.N." (Evidence Plausibly Supporting Theories Explaining Infection Naturality). It was intended be a humorous backronym. After receiving feedback from several readers, we have decided to change our name to "Project E" (Evidence) to avoid negative connotations with conspiracy theories. We maintain that this document is still supported by the best evidence we have been able to locate.
