### ISSUE TITLE
Add'l Wuhan CDC for 8.2

### ISSUE THREAD

**Issue by sb777** [Project-Evidence/project-evidence.github.io#6]
Great work on this.

In "8.2 Suspected Laboratories", you should consider adding the map for the Wuhan CDC closer to the market. This is the one referred to in the Botao Xiao and Lei Xiao paper, but it doesn't show up on Google Maps.

You can verify the address in the author information of this paper: https://www.medrxiv.org/content/10.1101/2020.03.14.20036129v1.full.pdf

Wuhan Center for Disease Prevention and Control, 288 Machang Road

![EUjENAYWoAEtY6n-2](https://user-images.githubusercontent.com/10205537/79539534-e83ed580-805c-11ea-8bd2-863644877377.jpeg)

^The pin in the above image isn't dropped directly on the building. In the Xiao paper they draw a direct line.

**Comment by Project-Evidence** [comment]
Thank you very much. We have incorporated your work into [Revision 2](project-evidence.github.io).

**Comment by sb777** [comment]
You're quite welcome. 

I'm not seeing that lab in the new update yet. Am I missing something? Revision 2 is at the same URL, right? https://project-evidence.github.io/
