### ISSUE TITLE
Additional paper for the HIV Inserts section

### ISSUE THREAD

**Issue by sbellem** [Project-Evidence/project-evidence.github.io#7]
It may be relevant to mention this paper, perhaps in the [HIV Inserts](https://project-evidence.github.io/#%28part._hiv-inserts%29) section:

**Angiotensin-converting enzyme 2 (ACE2) proteins of different bat species confer variable susceptibility to SARS-CoV entry**

### Sources
* https://link.springer.com/article/10.1007/s00705-010-0729-6
* https://www.ncbi.nlm.nih.gov/pubmed/20567988

### Excerpts
Some, perhaps, relevant excerpts:

> Here, we extended our previous study to ACE2 molecules from seven additional bat species and tested their interactions with human SARS-CoV spike protein using both HIV-based pseudotype and live SARS-CoV infection assays. The results show that ACE2s of Myotis daubentoni and Rhinolophus sinicus support viral entry mediated by the SARS-CoV S protein, albeit with different efficiency in comparison to that of the human ACE2. 

> **Functionality of bat ACE2 as an SARS-CoV entry receptor**
> To examine the susceptibility of different bat ACE2 molecules to SARs-CoV entry, the HIV/BJ01-S pseudovirus system was used to infect HeLa cells transiently expressing bat ACE2 or human ACE2 genes. Among the bat ACE2s, only MdACE2 (MdACE2) and Rs-HB ACE2 demonstrated significant pseudovirus infection, as deduced from the significantly higher level of luciferase activity in comparison to background activity in the negative control (Fig. 2a). Although such assays are not to be viewed as an absolute quantification of receptor activity, it is nevertheless worth noting that MdACE2-mediated infection seemed to be more efficient than with Rs-HB ACE2. In the same context, it is clear that the bat ACE2s were less efficient overall than the human ACE2 in this particular assay system. The biological significance of this observation remains to be determined. The functionality of MdACE2 and Rs-HB ACE2 as SARS-CoV entry receptors was further confirmed by infection with live virus. As shown in Fig. 2b, both bat ACE2 proteins could clearly support SARs-CoV infection. No attempt was made to quantify infection efficiency in this study due to difficulties encountered in conducting experiments under BSL4 conditions.

### Pull Request worthy?
If this is worthy of a pull request I can make one.

### Disclaimer
I do not have any substantial relevant knowledge. I just wish to help, as someone who lives on a planet that may be under a great danger that may be underestimated.

**Comment by sbellem** [comment]
> Professor Luc Montagnier, 2008 Nobel Prize winner for Medicine, claims that SARS-CoV-2 is a manipulated virus that was accidentally released from a laboratory in Wuhan, China.
--https://www.gilmorehealth.com/chinese-coronavirus-is-a-man-made-virus-according-to-luc-montagnier-the-man-who-discovered-hiv/

https://www.zerohedge.com/health/covid-19-man-made-virus-hiv-discoverer-says-could-only-have-been-created-lab

**Comment by sbellem** [comment]
@isometric Thanks for providing feedback. As I mention above I do not have domain knowledge for this problem, but simply wish to help. It may be useful to provide explanations as to why an idea may not be seen as "good".

Until then, just in case this may be of some use, I would like to add links to the research paper that Luc Montagnier's collegue, Jean-Claude Perez released in preprint, and posted the links to on [twitter](https://twitter.com/JCPEREZCODEX/status/1237276756895301633):

* https://www.researchgate.net/publication/339331507_Wuhan_nCoV-2019_SARS_Coronaviruses_Genomics_Fractal_Metastructures_Evolution_and_Origins/stats#fullTextFileContent

A journal version is at https://zenodo.org/record/3724003 (WUHAN COVID-19 SYNTHETIC ORIGINS AND EVOLUTION.” International Journal of Research - Granthaalayah, 8(2), 285-324.)

I am sharing this because one major problem right now is that it is very difficult to understand what is going on and alternative hypotheses are very often labelled as conspiracy theories and then there is no discussion/explanation whatsoever as to why the hypothesis is flawed or unworthy of attention.

According to Jean-Claude Perez, reported in French news [Le Point](https://www.lepoint.fr/sante/le-virus-du-sars-cov-2-a-t-il-ete-cree-par-l-homme-tous-les-elements-pour-en-juger-18-04-2020-2371937_40.php), he and Luc Montagnier will soon release another paper: 

> Dans un article à venir, nous démontrons avec Luc Montagnier qu'il existe bien plus de 6 fragments VIH et SIV. Certains sont placés côte à côte avec une précision d'horloger.

This translates roughly as:

> In an article to come, we demonstrate with Luc Montagnier that there exists much more than 6 fragments of HIV and SIV. Some (fragments) are placed next to each other with a watchmaker precision.

**Comment by Project-Evidence** [comment]
This is very interesting. We are keen to see if any of these papers make it out of the pre-print stage and are accepted after peer review. Please keep us in the loop, although we suspect we will all hear of Jean-Claude Perez's paper if it is published :)

@sbellem We briefly touch on ACE2 receptors in Paper 3, although let us know if you think our coverage of them was inadequate.
