### ISSUE TITLE
Paper about gain-of-function properties

### ISSUE THREAD

**Issue by sbellem** [Project-Evidence/project-evidence.github.io#8]
Not sure if this fits in, as it may be related to the topic of the virus being bio-engineered, and furthermore, weaponized, but I share it, just in case.

**The spike glycoprotein of the new coronavirus 2019-nCoV contains a furin-like cleavage site absent in CoV of the same clade**

### Sources
* https://www.sciencedirect.com/science/article/pii/S0166354220300528
* https://www.ncbi.nlm.nih.gov/pubmed/32057769

[Francis Boyle](https://law.illinois.edu/faculty-research/faculty-profiles/francis-boyle/), who drafted the [Biological Weapons Anti-Terrorism Act of 1989](https://en.wikipedia.org/wiki/Biological_Weapons_Anti-Terrorism_Act_of_1989) pointed out this article, in an interview with Alex Jones ([transcript](https://www.naturalnews.com/2020-02-20-full-transcript-smoking-gun-interview-prof-frances-boyle-coronavirus-bioweapons.html)), and mentioned:

> And let me just conclude, the critical part here where it says, “and may provide a gain of function to the 2019 nCoV for efficient spreading in the human population compared to other beta coronaviruses.” Let me repeat that: “and may provide a gain of function to the 2019 nCoV for efficient spreading in the human population compared to other beta coronaviruses.”

The actual passage from the paper is:

> This furin-like cleavage site, is supposed to be cleaved during virus egress (Mille and Whittaker, 2014) for S-protein“priming”and may provide a gain-of-function to the 2019-nCoV for efficientspreading in the human population compared to other lineage b beta-coronaviruses.

Now, the **Bulletin of the Atomic Scientists** in [Why do politicians keep breathing life into the false conspiracy theory that the coronavirus is a bioweapon?](https://thebulletin.org/2020/03/why-do-politicians-keep-breathing-life-into-the-false-conspiracy-theory-that-the-coronavirus-is-a-bioweapon/) points out:

> A March 12 article in Britain’s Express tabloid added fuel to fire, reporting that University of Illinois law professor Francis Boyle, who helped draft the legislation that implemented the Biological Weapons Convention in the United States, had identified a “smoking gun” that showed the coronavirus was a bioweapon leaked from a Chinese research lab near Wuhan, the city where the outbreak originated. Boyle reportedly based his theory on a paper on ScienceDirect that noted a “gain-of-function” in the virus that makes it better than other coronaviruses at spreading among humans. But as the Express itself notes in a correction, the research paper Boyle cited does not speculate on what caused the gain-of-function in the virus. “It was therefore incorrect when our article claimed ‘the paper suggested Covid-19 has been tampered with,’” the correction notes.

### Pull Request worthy?
If this is worthy of a pull request I can make one.

### Disclaimer
I do not have any substantial relevant knowledge. I just wish to help, as someone who lives on a planet that may be under a great danger that may be underestimated.

**Comment by Project-Evidence** [comment]
Thank you for contributing. The statement that "the spike glycoprotein of the new coronavirus 2019-nCoV contains a furin-like cleavage site absent in CoV of the same clade" appears to be legitimate. However, we cannot find independent confirmation outside of Francis Boyle
 that this is proof of bio-engineering. All legitimate medical journals that we have seen have denied this possibility.

Nevertheless, with this discovery and more being made every day, it may become apparent that the virus has evolved or been manipulated by humans in subtle ways. If such evidence appears, we have full confidence that the scientific community will see it for what it is and revise their conclusions appropriately.
